# Generated by Django 5.2.6 on 2025-09-11 04:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('height', models.SmallIntegerField(blank=True, null=True)),
                ('weight', models.SmallIntegerField(blank=True, null=True)),
                ('side', models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Left'), (2, 'Right')], default=0)),
                ('profile_picture_url', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'db_table': 'person',
                'indexes': [models.Index(fields=['phone'], name='person_phone_e491f7_idx'), models.Index(fields=['name'], name='person_name_b6df79_idx')],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'team',
                'indexes': [models.Index(fields=['name'], name='team_name_53aa8f_idx'), models.Index(fields=['is_active'], name='team_is_acti_74834d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.IntegerField(choices=[(1, 'Player'), (2, 'Captain'), (3, 'Coach'), (4, 'Manager')], default=1)),
                ('joined_at', models.DateField(blank=True, null=True)),
                ('left_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.person')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.team')),
            ],
            options={
                'db_table': 'person_team',
                'indexes': [models.Index(fields=['team', 'is_active'], name='person_team_team_id_37389f_idx'), models.Index(fields=['person', 'is_active'], name='person_team_person__78883a_idx')],
                'constraints': [models.UniqueConstraint(fields=('person', 'team'), name='uq_person_team_once')],
            },
        ),
    ]
