# Generated by Django 5.2.6 on 2025-09-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='person',
            name='side',
            field=models.SmallIntegerField(choices=[(0, 'Both'), (1, 'Left'), (2, 'Right')], default=0),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(('height__gte', 0)), name='ck_person_height_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 0)), name='ck_person_weight_nonneg'),
        ),
    ]
