# Generated by Django 5.2.6 on 2025-09-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_person_phone_alter_person_side_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='max_members',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
