# Generated by Django 5.2.6 on 2025-09-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_team_max_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.RemoveIndex(
            model_name='membership',
            name='person_team_team_id_37389f_idx',
        ),
        migrations.RemoveIndex(
            model_name='membership',
            name='person_team_person__78883a_idx',
        ),
        migrations.RemoveIndex(
            model_name='team',
            name='team_is_acti_74834d_idx',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='joined_at',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='left_at',
        ),
        migrations.RemoveField(
            model_name='team',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='team',
            name='max_members',
            field=models.PositiveIntegerField(blank=True, default=22),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['team'], name='person_team_team_id_565181_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['person'], name='person_team_person__5114e3_idx'),
        ),
    ]
