# Generated by Django 5.2.6 on 2025-09-24 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_team_options_remove_team_team_name_53aa8f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('name', models.CharField(max_length=255)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.team')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('start_at', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainings', to='api.location')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='api.team')),
            ],
            options={
                'ordering': ['-start_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['team'], name='api_locatio_team_id_76229e_idx'),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['team', 'start_at'], name='api_trainin_team_id_ea01d4_idx'),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['start_at'], name='api_trainin_start_a_5944c2_idx'),
        ),
    ]
