# Generated by Django 5.2.6 on 2025-09-24 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_location_training_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='location',
            new_name='location_team_id_333304_idx',
            old_name='api_locatio_team_id_76229e_idx',
        ),
        migrations.RenameIndex(
            model_name='training',
            new_name='training_team_id_880218_idx',
            old_name='api_trainin_team_id_ea01d4_idx',
        ),
        migrations.RenameIndex(
            model_name='training',
            new_name='training_start_a_affcc4_idx',
            old_name='api_trainin_start_a_5944c2_idx',
        ),
        migrations.AlterModelTable(
            name='location',
            table='location',
        ),
        migrations.AlterModelTable(
            name='training',
            table='training',
        ),
    ]
