# Generated by Django 5.2.6 on 2025-09-25 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_api_locatio_team_id_76229e_idx_location_team_id_333304_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('state', models.SmallIntegerField(choices=[(1, 'Draft'), (2, 'Published')], default=1)),
                ('training', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lineup', to='api.training')),
            ],
            options={
                'db_table': 'lineup',
            },
        ),
        migrations.CreateModel(
            name='LineupSeat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('side', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], max_length=1)),
                ('seat_number', models.SmallIntegerField()),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='api.lineup')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_seats', to='api.person')),
            ],
            options={
                'db_table': 'lineup_seat',
            },
        ),
        migrations.AddIndex(
            model_name='lineup',
            index=models.Index(fields=['state'], name='lineup_state_b8f9c4_idx'),
        ),
        migrations.AddIndex(
            model_name='lineupseat',
            index=models.Index(fields=['lineup', 'side'], name='lineup_seat_lineup__053923_idx'),
        ),
        migrations.AddIndex(
            model_name='lineupseat',
            index=models.Index(fields=['lineup', 'person'], name='lineup_seat_lineup__6d9092_idx'),
        ),
        migrations.AddConstraint(
            model_name='lineupseat',
            constraint=models.UniqueConstraint(fields=('lineup', 'side', 'seat_number'), name='uq_lineup_side_seat'),
        ),
        migrations.AddConstraint(
            model_name='lineupseat',
            constraint=models.UniqueConstraint(condition=models.Q(('person__isnull', False)), fields=('lineup', 'person'), name='uq_lineup_person_once'),
        ),
    ]
