# Generated by Django 5.2.6 on 2026-07-19 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_team_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=8, unique=True),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attended', models.BooleanField(default=False)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='api.membership')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='api.training')),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['training', 'membership'],
                'constraints': [models.UniqueConstraint(fields=('membership', 'training'), name='unique_membership_training')],
            },
        ),
    ]
