# Generated by Django 5.2.6 on 2026-07-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineupseat',
            name='side',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('D', 'Drummer'), ('S', 'Steerer')], max_length=1),
        ),
        migrations.AddConstraint(
            model_name='lineupseat',
            constraint=models.UniqueConstraint(condition=models.Q(('side__in', ['D', 'S'])), fields=('lineup', 'side'), name='uq_lineup_single_special'),
        ),
    ]
