FROM node:20-bullseye
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Copy .env.aws to .env.development so Vite uses it
COPY .env.aws .env.development

EXPOSE 5174

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5174"]