spring:
    application:
        name: dragon-backend

    datasource:
        url: jdbc:postgresql://localhost:5432/${DB_NAME:dragon_dev}
        username: ${DB_USER:dragon_user}
        password: ${DB_PASSWORD:dragon_pass}
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update  # Use 'validate' in production
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
        open-in-view: false

    jackson:
        serialization:
            write-dates-as-timestamps: false
        time-zone: UTC

server:
    port: 8080
    error:
        include-message: always
        include-binding-errors: always

# JWT Configuration
jwt:
    secret: your-256-bit-secret-key-change-this-in-production
    expiration: 900000  # 15 minutes in milliseconds
    refresh-expiration: 604800000  # 7 days in milliseconds

logging:
    level:
        com.dragon.backend: DEBUG
        org.hibernate.SQL: DEBUG
        org.springframework.web: DEBUG